### ISSUE TITLE
ProgrammingError caused by _pgh_attach_context from create_event when using denormalized context 

### ISSUE THREAD

**Issue by benjamin-kicker-cloud** [Opus10/django-pghistory#115]
When using a denormalized context, the `create_event` function results in `ProgrammingError: column "pgh_context" is of type jsonb but expression is of type uuid`. The `_pgh_attach_context` procedure returns `_pgh_context_id` (the uuid of the context) instead of the context data itself).

Django==4.2.10
django-pgtrigger==4.11.0
django-pghistory==3.1.0
psycopg==3.1.18

**Comment by wesleykendall** [comment]
Thanks for reporting. This has been fixed and will be available in 3.4.0
