### ISSUE TITLE
How to ignore/disable eventing dynamically ?

### ISSUE THREAD

**Issue by JimFuller-RedHat** [Opus10/django-pghistory#116]
Is there a baked in idiom for suspending tracking ?

example psuedocode

```
with pghistory.ignore():
    # do stuff
```

Similar question - is there a way to temporarily disable all event tracking (perhaps with setting of a django config) ?

Or maybe this is best done at the pg level with `ALTER TABLE table_name DISABLE TRIGGER ALL;` or some variant ...

thx in advance

**Comment by ivanbrizuela** [comment]
Events are tracked using `django-pgtrigger` package.

See [django-pgtrigger - Ignoring triggers](https://django-pgtrigger.readthedocs.io/en/4.9.0/ignoring_triggers/)

```python
with pgtrigger.ignore($TRIGGER_URI(S)):
    # Now execute code ignoring trigger(s)
```
