### ISSUE TITLE
Is there a way to override the name of the db table used for capturing history?

### ISSUE THREAD

**Issue by sshivananda** [Opus10/django-pghistory#14]
It looks like the event table that gets created defaults to the db table name of `${app_label_model_name}_event`. Is there a way to override the name of the table that gets generated?

From a reading of the code , it seems like `create_event_model` allows for the `meta` attribute to be passed in - but this option isn't currently exposed in the top level functions (`track` ?)

**Comment by melvyn-oviavo** [comment]
`track` and `get_event_model` complement and use each other. If you don't care about the event model, use track. If you do, use get_event_model. See [the documentation](https://django-pghistory.readthedocs.io/en/latest/tutorial.html#creating-a-custom-event-model).

**Comment by xjlin0** [comment]
Yes, you can do it by[ creating custom Event model](https://django-pghistory.readthedocs.io/en/latest/tutorial.html#creating-a-custom-event-model) with class Meta. For example
```
class MySnapshotModel(pghistory.get_event_model(
    TestModel,
    pghistory.Snapshot('test_model.snapshot'),
)):
    pgh_id = models.BigAutoField(primary_key=True, serialize=False)
    pgh_created_at = models.DateTimeField(auto_now_add=True)
    pgh_label = models.TextField(help_text='The event label.')
    pgh_context = models.ForeignKey(db_constraint=False, null=True, on_delete=django.db.models.deletion.DO_NOTHING, related_name='+', to='pghistory.context')
    pgh_obj = models.ForeignKey(db_constraint=False, on_delete=django.db.models.deletion.DO_NOTHING, related_name='event', to='app_name.test_model')
    # whatever columns you needs

    class Meta:
        db_table = "your_favorite_table_name"
```
