### ISSUE TITLE
Errors when createing or deleting child models

### ISSUE THREAD

**Issue by xaitec** [Opus10/django-pghistory#161]
I have some concrete inheritance models that i am using but am unable to create any new objects. When i try to save i get the following message:

`ProgrammingError: record "new" has no field "acting"
CONTEXT:  SQL statement "INSERT INTO "employee_services_allowancesummaryevent" ("acting", "active", "allowance_type", "allowance_value", "appraisal_state", "approval_date", "assumption_date", "continuous", "created", "created_by_id", "employee_id", "employment_type", "employmentsummary_ptr_id", "end", "id", "justification_id", "modified", "notes", "percentage_of_salary_scale", "pgh_context_id", "pgh_created_at", "pgh_label", "pgh_obj_id", "position_id", "post_id", "report_to_id", "salary_scale_id", "start", "summary_document", "summary_type", "verified_by_id", "verified_date") VALUES (NEW."acting", NEW."active", NEW."allowance_type", NEW."allowance_value", NEW."appraisal_state", NEW."approval_date", NEW."assumption_date", NEW."continuous", NEW."created", NEW."created_by_id", NEW."employee_id", NEW."employment_type", NEW."employmentsummary_ptr_id", NEW."end", NEW."id", NEW."justification_id", NEW."modified", NEW."notes", NEW."percentage_of_salary_scale", _pgh_attach_context(), NOW(), 'insert', NEW."employmentsummary_ptr_id", NEW."position_id", NEW."post_id", NEW."report_to_id", NEW."salary_scale_id", NEW."start", NEW."summary_document", NEW."summary_type", NEW."verified_by_id", NEW."verified_date")"
PL/pgSQL function pgtrigger_insert_insert_2f834() line 11 at SQL statement`

I assume that the "acting" field shows as it is the first field alphabetically.

I also tested deleting and got the following:
`ProgrammingError: record "old" has no field "acting"
CONTEXT:  SQL statement "INSERT INTO "employee_services_actingsummaryevent" ("acting", "active", "appraisal_state", "approval_date", "assumption_date", "continuous", "created", "created_by_id", "employee_id", "employment_type", "employmentsummary_ptr_id", "end", "id", "justification_id", "modified", "pgh_context_id", "pgh_created_at", "pgh_label", "pgh_obj_id", "position_id", "post_id", "salary_scale_id", "start", "summary_document", "summary_type", "verified_by_id", "verified_date") VALUES (OLD."acting", OLD."active", OLD."appraisal_state", OLD."approval_date", OLD."assumption_date", OLD."continuous", OLD."created", OLD."created_by_id", OLD."employee_id", OLD."employment_type", OLD."employmentsummary_ptr_id", OLD."end", OLD."id", OLD."justification_id", OLD."modified", _pgh_attach_context(), NOW(), 'delete', OLD."employmentsummary_ptr_id", OLD."position_id", OLD."post_id", OLD."salary_scale_id", OLD."start", OLD."summary_document", OLD."summary_type", OLD."verified_by_id", OLD."verified_date")"
PL/pgSQL function pgtrigger_delete_delete_b7fdb() line 11 at SQL statement`

Also I get no problems updateing existing models. 

I would like to add that this only happens for child models, the parent works as expected.

**Comment by wesleykendall** [comment]
@xaitec is it possible to provide an example parent/child model so I can reproduce this behavior?

Also, is it the parent or child that has `pghistory.track` on it?

pghistory doesn't have the greatest support for concrete inheritance, but this seems like a bug

**Comment by wesleykendall** [comment]
Let me see if I can reproduce this. I have a feeling that this PR https://github.com/Opus10/django-pghistory/pull/36 I closed may have solved some of these issues.

For concrete inheritance, there are multiple tables managed underneath. The snapshots for `ActingSummary` will only contain the parent ID, `id`, `assumption_date`, and `continuous`. If one makes changes to both parent/child at once, you'd have to rely on [context tracking](https://django-pghistory.readthedocs.io/en/3.4.0/context/) to understand the full change across two tracking tables.

If this is going to be problematic for your use case, abstract modeling/inheritance would be better since the table for `ActingSummary` would include all fields and not rely on a foreign key to a parent table.

FYI it's likely I won't be able to check out this issue until tomorrow. Will report back

**Comment by xaitec** [comment]
I cant yet say if it will be a problem to implement as i'm not entirely sure how to implement it. 

Tomorrow is fine to look into it as I am not on a time constraint.

**Comment by wesleykendall** [comment]
I made a simple test case to reproduce this in pghistory. Seems to only matter when tracking all fields on concrete child models. Should be fixed in 3.4.2. Let me know if you have any more issues!
