### ISSUE TITLE
Incorrect type hint

### ISSUE THREAD

**Issue by melvyn-apryl** [Opus10/django-pghistory#17]
https://github.com/Opus10/django-pghistory/blob/3db57e53f2eceb89d3c92c0b40f6ed6936c4e26c/pghistory/core.py#L221

Preferably add actual type hints, but if that's not your cup of tea, this should be `Type[models.Model]`.

**Comment by wesleykendall** [comment]
Following up on some stale issues. Although pghistory isn't fully type hinted, most of the core functions are. I combed through some of the primary interface and corrected some of the types at https://github.com/Opus10/django-pghistory/pull/143 too. Will deploy this in the upcoming release
