### ISSUE TITLE
Reverse setup doesn't install triggers

### ISSUE THREAD

**Issue by melvyn-apryl** [Opus10/django-pghistory#19]
Docs of `get_event_model`:

>Instead of using pghistory.track, which dynamically generates an event model, one can instead construct a event model themselves, which will also set up event tracking for the original model.

The second part isn't working. The triggers are not installed after migrating (\dft shows none).

**Comment by wesleykendall** [comment]
@melvyn-apryl are you able to provide more information and verify this is still not working for you? I'm unable to reproduce it. The [test suite]](https://github.com/Opus10/django-pghistory/blob/811e327ab4f31bb1a35b79c89dfc3c25c6bbd397/pghistory/tests/models.py#L77) also uses a custom event model and verifies triggers are installed

**Comment by melvyn-apryl** [comment]
It's been a year and I don't recall the circumstances, sorry. I abandoned the approach after two-three tries. I don't even remember why I wanted to use this approach. If I do, I'll try to reproduce. For now, let's consider it closed.
