### ISSUE TITLE
Enable context for delete requests

### ISSUE THREAD

**Issue by sshivananda** [Opus10/django-pghistory#20]
Currently the [HistoryMiddleware adds the context only for PUT, PATCH and POST requests](https://github.com/Opus10/django-pghistory/blob/master/pghistory/middleware.py#L31). 

Is it possible to update this to also add context to delete requests?

**Comment by wesleykendall** [comment]
All core requests types are enabled now (GET, DELETE, POST, PUT, PATCH), and they can be configured with `PGHISTORY_MIDDLEWARE_METHODS`
