### ISSUE TITLE
Add a templatetag to retrieve aggregate events easily in the admin templates

### ISSUE THREAD

**Issue by pierreben** [Opus10/django-pghistory#34]
As explained in the documentation, it can be relevant to use a templatetag to retrieve the AggregateEvent objects directly in the context of the `admin/object_history.html` template.

I'd like to propose a PR to add such templatetag (coming in next minutes).

**Comment by wesleykendall** [comment]
Following up on some stale issues. This request was originally created before pghistory had an admin integration. If there are any limitations or proposed features with the admin that make sense in the core library, I've added [discussions](https://github.com/opus10/django-pghistory) to this repo. Feel free to open one there!
