### ISSUE TITLE
Interaction with Django Admin Log to give a richer Model Change History

### ISSUE THREAD

**Issue by dnk8n** [Opus10/django-pghistory#4]
Seems to me that when this library is installed it could supersede the default Django Admin log functionality (`django_admin_log` table).

My aim in using this library is for Django history to give a more detailed explanation of what happened, i.e.

DATE/TIME | USER | ACTION | ORIGINAL VALUE | CURRENT VALUE
-- | -- | -- | -- | -- 
June 18, 2020, 9:04 p.m. | stefan | Added Country Name | - | South Africa
June 18, 2020, 9:04 p.m. | stefan | Added Country Alpha 2 code | - | ZT
June 18, 2020, 9:04 p.m. | stefan | Added Country Alpha 3 code | - | ZAX
June 19, 2020, 9:04 a.m. | peter | Changed Country Alpha 3 code | ZAX | ZAF
June 19, 2020, 10:00 a.m. | - | Changed Country Alpha 2 code | ZT | ZA

Where in the case the admin directly made a change to the database, bypassing Django then obviously there would be no USER available (hence `-` above).

I really like that I have access to all of the above information in Country Event table but a bit confused about the final step. Any guidance available? I think this would be a very useful demonstration of the power of this library (if the above is possible or worthwhile using this library instead of another).

**Comment by wesleykendall** [comment]
There's a short example of how to integrate it into the admin [here](https://django-pghistory.readthedocs.io/en/latest/extras.html#showing-event-history-in-the-django-admin), and it should support a similar style as to what you're showing. The key difference is that it won't make a different row for each column and instead show a diff.

I'm planning on making a full drop-in replacement for the admin as a separate package that's maintained. Will keep this open until that's done

**Comment by wesleykendall** [comment]
Following up on some stale issues - pghistory has had an integrated admin for a while now, docs at https://django-pghistory.readthedocs.io/en/3.3.0/admin/#event-model-admin-pages.

It shows an "Events" button next to the built-in "History" button (which I believe can be configured to be turned off).
