### ISSUE TITLE
Triggers not added while applying migrations

### ISSUE THREAD

**Issue by Abhishekaubergine** [Opus10/django-pghistory#46]
I have followed the installation steps mentioned in the [documentation](https://django-pghistory.readthedocs.io/en/stable/installation.html). And I have tried to use [Tracking Snapshots of Models When Fields Change](https://django-pghistory.readthedocs.io/en/stable/tutorial.html#tracking-snapshots-of-models-when-fields-change).
Somehow this is not working, It is creating its event table but it's not populating on modal change nor I can find a trigger anywhere in the table.

Could you please help me with this?

**Comment by kevintand** [comment]
I face similar problem, then i found this issue and solved 
https://github.com/Opus10/django-pghistory/issues/39

**Comment by Abhishekaubergine** [comment]
@kevintand, Thanks for the reply. I tired adding `pgtrigger` and `pgconnection` to INSTALLED_APPS but still not working for me.

**Comment by Abhishekaubergine** [comment]
@kevintand, tried re-migrating it multiple time but isn't working for me. There wasn't any trigger added during migration.

**Comment by wesleykendall** [comment]
@Abhishekaubergine can answer the following?

1. What versions of pgtrigger and pghistory you are using?
2. If you're using `>=2` for `pghistory`, did you run `makemigrations`? If so, do you see `AddTrigger` operations in those migrations?
3. Are you tracking a model from a third-party app like Django's User model?

Finally, if you could report the output of `python manage.py pgtrigger ls`, that would also help narrow down the issue.

**Comment by wesleykendall** [comment]
Going to mark this as a question for now and will keep it open. Thanks for the patience.
