### ISSUE TITLE
Fix docs to mention that pgtrigger must be in INSTALLED_APPS

### ISSUE THREAD

**Issue by duebbert** [Opus10/django-pghistory#57]
Currently the installation instructions just say that `pghistory` needs to be added to the INSTALLED_APPS: https://django-pghistory.readthedocs.io/en/latest/installation.html

But doing only that will not the triggers in the migration, leaving new users scratching their heads why this is happening.

Simple fix is to change the sentence about adding pghistory to INSTALLED_APPS to:

     After this, add `pghistory` and `pgtrigger` to the `INSTALLED_APPS` setting of your Django project.

#39 #46

**Comment by wesleykendall** [comment]
Thanks for letting me know! I fixed this in https://github.com/Opus10/django-pghistory/pull/60, and I also added a check to Django's check framework to ensure that `pgtrigger` is in `INSTALLED_APPS` when pghistory is installed. Will close this when the fix is deployed
