### ISSUE TITLE
3rd party app objects' history is not viewable in Django Amin

### ISSUE THREAD

**Issue by xjlin0** [Opus10/django-pghistory#62]
Thanks again for the ["Showing Event History in the Django Admin" documentation](https://django-pghistory.readthedocs.io/en/latest/extras.html#showing-event-history-in-the-django-admin) for easy history browsing in Django Admin.  

However, for both django-pghistory 1.5 or 2.4 on Django 3.2, when clicking object history of 3rd party app, the custom history_view is not called and Django admin site shows original object_history.html:
```
This object doesn’t have a change history. It probably wasn’t added via this admin site.
```

For example, here is the code to add snapshot of Group model in django-pghistory 2
```python
from django.apps import apps as django_apps

@pghistory.track(
    pghistory.Snapshot('group.snapshot'),
)
class GroupProxy(django_apps.get_model("auth.Group", require_ready=False)):
    class Meta:
        proxy = True
```

In the database level, the correct history data are stored in the event table, however, it's not accessible in the Django Admin.

**Comment by wesleykendall** [comment]
@xjlin0 you're welcome! I'm actually working on integrating pghistory directly with the Django admin so that users no longer have to follow that example in the docs. 

Was the admin previously showing the correct history? Can you verify that you overrode the Group admin's `history_view` method as noted in the docs?

If you have it working for other models but it still fails for this one even after overriding the admin, I have a feeling it's related to the proxy models.

**Comment by xjlin0** [comment]
Hi @wesleykendall  thanks for your reply. An out-of-box admin UI will be great!

Sorry I just found out there's NO issues at all.  I forgot to [unregister/reregister 3rd party Admin class](https://stackoverflow.com/a/53360721/4257237).  What should be done for GroupAdmin is like:
```python
from django.contrib.auth.models import Group
from django.contrib.auth.admin import GroupAdmin

admin.site.unregister(Group)

class GroupAdmin(PgHistoryPage, GroupAdmin):
    pass

admin.site.register(Group,GroupsAdmin)
```
ps. PgHistoryPage class is [the object_history_template and history_view in the doc](https://django-pghistory.readthedocs.io/en/latest/extras.html#showing-event-history-in-the-django-admin).
