### ISSUE TITLE
How to track deletion events with snapshot?

### ISSUE THREAD

**Issue by xjlin0** [Opus10/django-pghistory#64]
Hi there,
It's been great using this great library, especially on the version 2.4, thanks for all your efforts!

Question: how do I track DELETE event along with snapshot?

My Event model definition:
```python
class ModelsEvent(pghistory.get_event_model(
    Model,
    pghistory.Snapshot('model.snapshot'),
)):
```
This only generates triggers for create and update, but not delete:
```python
pgtrigger.migrations.AddTrigger(
            model_name='model',
            trigger=pgtrigger.compiler.Trigger(name='model_snapshot_insert', .....
),
pgtrigger.migrations.AddTrigger(
            model_name='model',
            trigger=pgtrigger.compiler.Trigger(name='model_snapshot_update'....
```

**Comment by sebastienvercammen** [comment]
This works for me:
```py
@pghistory.track(
    pghistory.Snapshot('mymodel.snapshot'),
    pghistory.BeforeDelete('mymodel.before_delete'),
)
class MyModel(models.Model):
    pass
```

* [Snapshot docs](https://django-pghistory.readthedocs.io/en/latest/tutorial.html#tracking-snapshots-of-models-when-fields-change)
* [BeforeDelete docs](https://django-pghistory.readthedocs.io/en/latest/package.html?highlight=BeforeDelete#pghistory.BeforeDelete)

**Comment by xjlin0** [comment]
Thanks, I can confirm that @sebastienvercammen 's suggestion works.
