### ISSUE TITLE
Multiple trackers with DRF

### ISSUE THREAD

**Issue by jzmiller1** [Opus10/django-pghistory#68]
Making a note here in case someone encounters something similar. 

With an out of the box setup for pghistory with the admin integration enabled I am running multiple trackers on a model.  

```
@pghistory.track(
    pghistory.Snapshot(label='ap.snapshot'),
    pghistory.BeforeDelete(label='ap.beforedelete')
)
```

I have a DRF endpoint using filters that uses my ap model.  The endpoint results in the pg history error: 

ap has more than one tracker. Use the pgh_event_models dictionary to retrieve the event model by label.

Stemming from rest_framework/filters.py in get_default_valid_fields at line 230:
```

        model_property_names = [
            # 'pk' is a property added in Django's Model class, however it is valid for ordering.
            attr for attr in dir(model_class) if isinstance(getattr(model_class, attr), property) and attr != 'pk'
        ]
```

**Comment by wesleykendall** [comment]
I'm following up on some issues I left stale. There have been a lot of changes since this was reported, and Im not totally sure how to recreate this one. If anyone encounters this and it is still an issue, feel free to re-open this and I will see if I can add a failing test for it in the suite
