### ISSUE TITLE
BeforeDelete trigger raises IntegrityError on NEW.id (should be OLD.id)

### ISSUE THREAD

**Issue by geoff-lawn** [Opus10/django-pghistory#9]
Hi there,

From reading the trigger created for logging a delete event, it looks like it should be referencing OLD.id but is using NEW.id which is set to null on a delete.

My model:

class Branch(models.Model):
    occ_version = models.IntegerField(default=0)
    name = models.CharField(unique=True, max_length=30, blank=False)
    address = models.TextField(max_length=500, blank=True)
    manager = models.ForeignKey(User, null=True, on_delete=models.PROTECT)   

class Branch_delete_audit(pghistory.get_event_model(Branch, pghistory.BeforeDelete('branch.delete.audit'), related_name='branch_delete', )):
    pass

The error:

IntegrityError at /admin/acct/branch/2/delete/
null value in column "**pgh_obj_id**" violates not-null constraint
DETAIL:  Failing row contains (1, 2021-01-21 23:12:21.727031+00, branch.delete.audit, 2, Test office, some address, 2, 1, 0ffd0952-4676-4b16-b3eb-89a76d611e2a, null).
CONTEXT:  SQL statement "INSERT INTO "audit_branch_delete"
                ("occ_version", "name", "address", "manager_id", "id", "pgh_created_at", "pgh_label", "pgh_obj_id", "pgh_context_id") VALUES (OLD."occ_version", OLD."name", OLD."address", OLD."manager_id", OLD."id", NOW(), 'branch.delete.audit', **NEW."id"**, _pgh_attach_context())"
PL/pgSQL function pgtrigger_branch_delete_audit_c2919() line 14 at SQL statement

I believe the delete trigger that was generated by pghistory should read OLD.id when referring to the record that is to be deleted.

Thanks for your help, love your work!

**Comment by geoff-lawn** [comment]
Thanks Azurency, your fix works a charm.

**Comment by wesleykendall** [comment]
fixed in https://github.com/Opus10/django-pghistory/pull/26 and deployed in version 1.3.0

Thanks for the patience on this everyone!
