### ISSUE TITLE
Difference between Snapshot and AfterInsertOrUpdate

### ISSUE THREAD

**Issue by wgordon17** [Opus10/django-pghistory#92]
These both seem like they would serve the same use case, so I'm just struggling as to if there are subtle differences, or if they really _do_ solve the same use case.

**Comment by wesleykendall** [comment]
In earlier versions (`< 3`) of pghistory, these had a lot of overlap. `Snapshot`, however, would configure a default condition based on the tracked fields.

This has been addressed in [v3](https://django-pghistory.readthedocs.io/en/3.3.0/release_notes/#300-2023-10-16) as all trackers have been consolidated into `pghistory.InsertEvent`, `pghistory.UpdateEvent`, and `pghistory.DeleteEvent`.

Feel free to open a [discussion](https://github.com/Opus10/django-pghistory/discussions) if you encounter any confusion with the new interface
