### ISSUE TITLE
Doc request: FAQ on backfilling models with existing data

### ISSUE THREAD

**Issue by shangxiao** [Opus10/django-pghistory#94]
Suggestion: Add an FAQ on how to backfill audit events for models with existing data.

I saw this section in the docs on manual tracking, it helped me to add audit events for the current data I have: https://django-pghistory.readthedocs.io/en/2.7.0/event_tracking.html#manual-tracking

The FAQ could probably just link to that. Might also be worth noting that in the data migration you must refer to the actual model, not the fake model used in migration state, otherwise pghistory won't recognise it (there are no trackers on the fake models).

PS: Thanks for all the hard work on this useful lib 🏆

**Comment by tobiasmcnulty** [comment]
Thanks for creating this issue and linking to the solution!

A FAQ item for "backfilling events" or "populating initial events" sounds quite helpful to me, too.
