### ISSUE TITLE
Admin for MiddlewareEvents doesn't display non-mw events

### ISSUE THREAD

**Issue by pgcd** [Opus10/django-pghistory#97]
We need to track changes to a model that might happen both in normal views (so via middleware) and in shell or other operations.
As far as I can tell from the code and the docs, MiddlewareEvents should do just that, but what actually happens is this:
![image](https://github.com/Opus10/django-pghistory/assets/2361956/963a1c7d-9278-46a2-b150-647f5c860e89)

That is: the one event that I triggered via the admin is properly displayed; the other is filtered out and only counted.

Is there any workaround for this?

**Comment by wesleykendall** [comment]
Fixed in v3.3.0
