### ISSUE TITLE
django.db.utils.ProgrammingError: relation "pghistory_context" already exists

### ISSUE THREAD

**Issue by JRileyH** [Opus10/django-pghistory#99]
When restarting a dockerized instance of Django, the pghistory migrations are not properly idempotent. Requires clearing the DB before I can launch the app again.

**Comment by wesleykendall** [comment]
I double checked and there are no instances where the migrations in `pghistory` would cause the `pghistory_context` table to be re-built. All migration were created with the migration system except for `0004` which just installs the context tracking func.

I also use pghistory frequently with pytest-django and `--reuse-db`/`--create-db`, which I imagine would exercise this scenario.

If I'm missing something and you can provide a way to replicate this, let me know!
